"""add cascade

Revision ID: 8debf209aaf5
Revises: 6ad9f5ddbf6c
Create Date: 2025-05-02 12:06:18.443883

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""

from alembic import op

revision = "8debf209aaf5"
down_revision = "6ad9f5ddbf6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_chat_members_user_id_users", "chat_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_chat_members_user_id_users"), "chat_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("fk_groups_creator_id_users", "groups", type_="foreignkey")
    op.drop_constraint("fk_groups_chat_id_chats", "groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_groups_creator_id_users"), "groups", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(op.f("fk_groups_chat_id_chats"), "groups", "chats", ["chat_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("fk_message_seen_status_user_id_users", "message_seen_status", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_message_seen_status_user_id_users"),
        "message_seen_status",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_messages_sender_id_users", "messages", type_="foreignkey")
    op.drop_constraint("fk_messages_chat_id_chats", "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_messages_sender_id_users"), "messages", "users", ["sender_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("fk_messages_chat_id_chats"), "messages", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_messages_chat_id_chats"), "messages", type_="foreignkey")
    op.drop_constraint(op.f("fk_messages_sender_id_users"), "messages", type_="foreignkey")
    op.create_foreign_key("fk_messages_chat_id_chats", "messages", "chats", ["chat_id"], ["id"])
    op.create_foreign_key("fk_messages_sender_id_users", "messages", "users", ["sender_id"], ["id"])
    op.drop_constraint(op.f("fk_message_seen_status_user_id_users"), "message_seen_status", type_="foreignkey")
    op.create_foreign_key("fk_message_seen_status_user_id_users", "message_seen_status", "users", ["user_id"], ["id"])
    op.drop_constraint(op.f("fk_groups_chat_id_chats"), "groups", type_="foreignkey")
    op.drop_constraint(op.f("fk_groups_creator_id_users"), "groups", type_="foreignkey")
    op.create_foreign_key("fk_groups_chat_id_chats", "groups", "chats", ["chat_id"], ["id"])
    op.create_foreign_key("fk_groups_creator_id_users", "groups", "users", ["creator_id"], ["id"])
    op.drop_constraint(op.f("fk_chat_members_user_id_users"), "chat_members", type_="foreignkey")
    op.create_foreign_key("fk_chat_members_user_id_users", "chat_members", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
