"""add created_at to chat_members

Revision ID: a55287a14390
Revises: 8debf209aaf5
Create Date: 2025-05-04 10:08:47.501436

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""

import sqlalchemy as sa
from alembic import op

revision = "a55287a14390"
down_revision = "8debf209aaf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_members",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.alter_column("user_group", "created_at", server_default=sa.text("now()"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_members", "created_at")
    op.alter_column("user_group", "created_at", existing_server_default=None)
    # ### end Alembic commands ###
